services:
  postgres:
    image: pgvector/pgvector:pg18
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5453:5432
    volumes:
      - postgres_data:/var/lib/postgresql

  jaeger:
    image: jaegertracing/jaeger:latest
    ports:
      - 16686:16686
      - 9411:9411
      - 4317:4317
      - 4318:4318
      - 5778:5778
    environment:
      COLLECTOR_OTLP_ENABLED: ${COLLECTOR_OTLP_ENABLED:-true}
      COLLECTOR_OTLP_GRPC_HOST_PORT: 0.0.0.0:4317
      COLLECTOR_OTLP_HTTP_HOST_PORT: 0.0.0.0:4318
    networks:
      - monitoring
volumes:
  postgres_data:
  jaeger_data:

networks:
  monitoring:
    driver: bridge
