import http from "node:http";

const port = Number(process.env.PORT ?? 4010);

const server = http.createServer(async (request, response) => {
  if (request.method !== "POST" || request.url !== "/edge") {
    sendJson(response, 404, { body: "edge route not found" });
    return;
  }

  let payload;
  try {
    payload = JSON.parse(await readBody(request));
  } catch {
    sendJson(response, 400, { body: "invalid edge request" });
    return;
  }

  const path = new URL(payload.url).pathname;

  if (path === "/direct") {
    sendJson(response, 202, {
      body: "Direct response generated by the local edge API",
      headers: {
        "x-rendermesh-edge": "direct-body"
      }
    });
    return;
  }

  if (path === "/static.html" || path === "/legacy" || path.startsWith("/docs")) {
    sendJson(response, 200, {
      headers: {
        "x-rendermesh-edge": "static-pass-through"
      }
    });
    return;
  }

  if (path === "/file") {
    sendJson(response, 200, {
      file_path: "/static.html",
      headers: {
        "x-rendermesh-edge": "file-path"
      }
    });
    return;
  }

  sendJson(response, 200, {
    params: {
      eyebrow: "RenderMesh local lab",
      title: "HTML rendered with edge params",
      message: "This content came from the local edge API and was applied to index.html with Handlebars.",
      mode: "params"
    },
    headers: {
      "x-rendermesh-edge": "params"
    }
  });
});

server.listen(port, "0.0.0.0", () => {
  console.log(`local edge api listening on ${port}`);
});

function readBody(request) {
  return new Promise((resolve, reject) => {
    let body = "";
    request.setEncoding("utf8");
    request.on("data", (chunk) => {
      body += chunk;
    });
    request.on("end", () => resolve(body));
    request.on("error", reject);
  });
}

function sendJson(response, status, body) {
  response.writeHead(status, {
    "content-type": "application/json"
  });
  response.end(JSON.stringify(body));
}
